version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: patientdb
    environment:
      POSTGRES_DB: patientrecovery
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - patient-net

  app:
    build: target/generated-test-sources/test-annotations
    container_name: patientapp
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/patientrecovery
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    networks:
      - patient-net

volumes:
  pgdata:

networks:
  patient-net:
